web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'scm.dataascii.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://scm.dataascii.com'
      nginx['redirect_http_to_https'] = true
      nginx['ssl_certificate'] = "/etc/gitlab/ssl/#{node['fqdn']}.crt2"
      nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/#{node['fqdn']}.key2"

      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '9080:80'
    - '9443:443'
    - '9022:22'
  volumes:
    - '/home/nutt/Docker/gitlab/config:/etc/gitlab'
    - '/home/nutt/Docker/gitlab/logs:/var/log/gitlab'
    - '/home/nutt/Docker/gitlab/data:/var/opt/gitlab'
